//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.ReservationNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReservationNotificationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservationNotificationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.ReservationNotification.ReservationNotificationStrings", typeof(ReservationNotificationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guestbook Followup Notification.
        /// </summary>
        public static string GBF {
            get {
                return ResourceManager.GetString("GBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guestbook Notification.
        /// </summary>
        public static string GBK {
            get {
                return ResourceManager.GetString("GBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest of Guest Invitation Followup.
        /// </summary>
        public static string GGF {
            get {
                return ResourceManager.GetString("GGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest of Guest Invitation.
        /// </summary>
        public static string GGI {
            get {
                return ResourceManager.GetString("GGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Reservation.
        /// </summary>
        public static string OUP {
            get {
                return ResourceManager.GetString("OUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Invitation Followup.
        /// </summary>
        public static string PGF {
            get {
                return ResourceManager.GetString("PGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Invitation.
        /// </summary>
        public static string PGI {
            get {
                return ResourceManager.GetString("PGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Thank You Notification.
        /// </summary>
        public static string PGT {
            get {
                return ResourceManager.GetString("PGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Welcome Notification.
        /// </summary>
        public static string PGW {
            get {
                return ResourceManager.GetString("PGW", resourceCulture);
            }
        }
    }
}
