//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.Mobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobileStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.Mobile.MobileStrings", typeof(MobileStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access My Rental.
        /// </summary>
        public static string AccessMyRental {
            get {
                return ResourceManager.GetString("AccessMyRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Instructions will be provided within 14 days of your arrival assuming you are paid in full and have signed any contracts..
        /// </summary>
        public static string AccessMyRentalDefault {
            get {
                return ResourceManager.GetString("AccessMyRentalDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door code: &lt;b&gt;{0}&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;{1}.
        /// </summary>
        public static string AccessMyRentalTemplate {
            get {
                return ResourceManager.GetString("AccessMyRentalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATMs.
        /// </summary>
        public static string ATMs {
            get {
                return ResourceManager.GetString("ATMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Things To Do.
        /// </summary>
        public static string Attractions {
            get {
                return ResourceManager.GetString("Attractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worship.
        /// </summary>
        public static string Churches {
            get {
                return ResourceManager.GetString("Churches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the feedback!.
        /// </summary>
        public static string FeedbackThanks {
            get {
                return ResourceManager.GetString("FeedbackThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find My Rental.
        /// </summary>
        public static string FindMyRental {
            get {
                return ResourceManager.GetString("FindMyRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Stations.
        /// </summary>
        public static string GasStations {
            get {
                return ResourceManager.GetString("GasStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get The App.
        /// </summary>
        public static string GetTheApp {
            get {
                return ResourceManager.GetString("GetTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have an app for that! Search your app store for &quot;HomeAway&quot; or click below to get the iPhone/iPad and Android applications.  .
        /// </summary>
        public static string GetTheAppDescription {
            get {
                return ResourceManager.GetString("GetTheAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to text a link to download the free HomeAway mobile app..
        /// </summary>
        public static string GetTheAppText {
            get {
                return ResourceManager.GetString("GetTheAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Details.
        /// </summary>
        public static string GooglePlaces {
            get {
                return ResourceManager.GetString("GooglePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery Stores.
        /// </summary>
        public static string GroceryStores {
            get {
                return ResourceManager.GetString("GroceryStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions Powered By Google.
        /// </summary>
        public static string GTHYSuggested {
            get {
                return ResourceManager.GetString("GTHYSuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Star (Worst).
        /// </summary>
        public static string Guestbook_Rating_1 {
            get {
                return ResourceManager.GetString("Guestbook_Rating_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Stars.
        /// </summary>
        public static string Guestbook_Rating_2 {
            get {
                return ResourceManager.GetString("Guestbook_Rating_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Stars.
        /// </summary>
        public static string Guestbook_Rating_3 {
            get {
                return ResourceManager.GetString("Guestbook_Rating_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Stars.
        /// </summary>
        public static string Guestbook_Rating_4 {
            get {
                return ResourceManager.GetString("Guestbook_Rating_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Stars (Best).
        /// </summary>
        public static string Guestbook_Rating_5 {
            get {
                return ResourceManager.GetString("Guestbook_Rating_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Video.
        /// </summary>
        public static string HelpVideo {
            get {
                return ResourceManager.GetString("HelpVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        public static string Hospitals {
            get {
                return ResourceManager.GetString("Hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Others.
        /// </summary>
        public static string InviteOthers {
            get {
                return ResourceManager.GetString("InviteOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will receive an email shortly describing how to get signed-in..
        /// </summary>
        public static string InviteOthersResponse {
            get {
                return ResourceManager.GetString("InviteOthersResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite others staying with you to get access to this information..
        /// </summary>
        public static string InviteOthersText {
            get {
                return ResourceManager.GetString("InviteOthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone/iPod.
        /// </summary>
        public static string iOS {
            get {
                return ResourceManager.GetString("iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} kilometers from rental.
        /// </summary>
        public static string KilometersFromRental {
            get {
                return ResourceManager.GetString("KilometersFromRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Suggestions.
        /// </summary>
        public static string LocalSuggestions {
            get {
                return ResourceManager.GetString("LocalSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Weather.
        /// </summary>
        public static string LocalWeather {
            get {
                return ResourceManager.GetString("LocalWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string MainSite {
            get {
                return ResourceManager.GetString("MainSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Malls {
            get {
                return ResourceManager.GetString("Malls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N2} miles from rental.
        /// </summary>
        public static string MilesFromRental {
            get {
                return ResourceManager.GetString("MilesFromRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Theaters.
        /// </summary>
        public static string MovieTheaters {
            get {
                return ResourceManager.GetString("MovieTheaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Rental.
        /// </summary>
        public static string MyRental {
            get {
                return ResourceManager.GetString("MyRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stay.
        /// </summary>
        public static string MyStay {
            get {
                return ResourceManager.GetString("MyStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;icon-avatar-1&quot; style=&quot;color: #cccccc&quot;&gt;&lt;/i&gt; {0}&lt;br/&gt;&lt;br/&gt;
        ///&lt;i class=&quot;icon-mail-1&quot; style=&quot;color: #cccccc&quot;&gt;&lt;/i&gt; {1}&lt;br/&gt;&lt;br/&gt;
        ///&lt;i class=&quot;icon-calendar-empty&quot; style=&quot;color: #cccccc&quot;&gt;&lt;/i&gt; {2} - {3}&lt;br/&gt;&lt;br/&gt;
        ///&lt;i class=&quot;icon-accommodation&quot; style=&quot;color: #cccccc&quot;&gt;&lt;/i&gt; {4} in {5}&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string MyStayDetails {
            get {
                return ResourceManager.GetString("MyStayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rating.
        /// </summary>
        public static string NoRating {
            get {
                return ResourceManager.GetString("NoRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reservation was found matching that criteria..
        /// </summary>
        public static string NoReservationFound {
            get {
                return ResourceManager.GetString("NoReservationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions From Owner.
        /// </summary>
        public static string OwnerSuggested {
            get {
                return ResourceManager.GetString("OwnerSuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacies.
        /// </summary>
        public static string Pharmacies {
            get {
                return ResourceManager.GetString("Pharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Offices.
        /// </summary>
        public static string PostOffices {
            get {
                return ResourceManager.GetString("PostOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Arrival.
        /// </summary>
        public static string PreArrival {
            get {
                return ResourceManager.GetString("PreArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating {0}.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will receive an email shortly describing how to get signed-in..
        /// </summary>
        public static string ReinviteMessage {
            get {
                return ResourceManager.GetString("ReinviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent.
        /// </summary>
        public static string ReinviteTitle {
            get {
                return ResourceManager.GetString("ReinviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;{0} Day(s): &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        public static string RelevantDays {
            get {
                return ResourceManager.GetString("RelevantDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information has not been provided. We&apos;ve notified the owner that you are interested in this content. Please check back later..
        /// </summary>
        public static string RequestContent {
            get {
                return ResourceManager.GetString("RequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Review.
        /// </summary>
        public static string SignGuestbook {
            get {
                return ResourceManager.GetString("SignGuestbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a review. We&apos;d love to know more about you and your stay!.
        /// </summary>
        public static string SignGuestbookText {
            get {
                return ResourceManager.GetString("SignGuestbookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to download the HomeAway mobile application by {0}. {1}.
        /// </summary>
        public static string SMSInviteMessage {
            get {
                return ResourceManager.GetString("SMSInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Stay.
        /// </summary>
        public static string SwitchStay {
            get {
                return ResourceManager.GetString("SwitchStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentails are valid but you have not purchased access to the owners mobile. Please do so at owners.gladtohaveyou.com.
        /// </summary>
        public static string ValidCredentialsMobileNotEnabled {
            get {
                return ResourceManager.GetString("ValidCredentialsMobileNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reviews.
        /// </summary>
        public static string ViewGuestbook {
            get {
                return ResourceManager.GetString("ViewGuestbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
