//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.RentalContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentalContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentalContentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.RentalContent.RentalContentStrings", typeof(RentalContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your guests the story of your rental..
        /// </summary>
        public static string content_aboutowner_helptext {
            get {
                return ResourceManager.GetString("content_aboutowner_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to story, about.
        /// </summary>
        public static string content_aboutowner_keywords {
            get {
                return ResourceManager.GetString("content_aboutowner_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Owner.
        /// </summary>
        public static string content_aboutowner_title {
            get {
                return ResourceManager.GetString("content_aboutowner_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_accessrental_helptext {
            get {
                return ResourceManager.GetString("content_accessrental_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access, code, door, directions.
        /// </summary>
        public static string content_accessrental_keywords {
            get {
                return ResourceManager.GetString("content_accessrental_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access My Rental.
        /// </summary>
        public static string content_accessrental_title {
            get {
                return ResourceManager.GetString("content_accessrental_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your rental is near a beach let your guests know the easist and best ways to access the beach..
        /// </summary>
        public static string content_beachaccess_helptext {
            get {
                return ResourceManager.GetString("content_beachaccess_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beach, ocean, water, code.
        /// </summary>
        public static string content_beachaccess_keywords {
            get {
                return ResourceManager.GetString("content_beachaccess_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string content_beachaccess_title {
            get {
                return ResourceManager.GetString("content_beachaccess_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are any details like making reservations at restaurants, etc let them know here befor they leave to come to your rental.
        /// </summary>
        public static string content_beforeyouleave_helptext {
            get {
                return ResourceManager.GetString("content_beforeyouleave_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive,arrival.
        /// </summary>
        public static string content_beforeyouleave_keywords {
            get {
                return ResourceManager.GetString("content_beforeyouleave_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before You Visit.
        /// </summary>
        public static string content_beforeyouleave_title {
            get {
                return ResourceManager.GetString("content_beforeyouleave_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you provide bikes with your rental or there are specifics about biking in your area let your guest know.  You could provide the best place to rent bikes from, etc..
        /// </summary>
        public static string content_biking_helptext {
            get {
                return ResourceManager.GetString("content_biking_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bike, rental, mountain.
        /// </summary>
        public static string content_biking_keywords {
            get {
                return ResourceManager.GetString("content_biking_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biking.
        /// </summary>
        public static string content_biking_title {
            get {
                return ResourceManager.GetString("content_biking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you provide a boat with your rental or there are specifics about boating in your area let your guest know.
        /// </summary>
        public static string content_boating_helptext {
            get {
                return ResourceManager.GetString("content_boating_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boat, fish, dock.
        /// </summary>
        public static string content_boating_keywords {
            get {
                return ResourceManager.GetString("content_boating_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boating.
        /// </summary>
        public static string content_boating_title {
            get {
                return ResourceManager.GetString("content_boating_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the guest details on what is required to check-in to your property.  Also provide details for early or late arrival..
        /// </summary>
        public static string content_checkin_helptext {
            get {
                return ResourceManager.GetString("content_checkin_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkin, arrive, arrival.
        /// </summary>
        public static string content_checkin_keywords {
            get {
                return ResourceManager.GetString("content_checkin_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        public static string content_checkin_title {
            get {
                return ResourceManager.GetString("content_checkin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let your guests know what they will need to do to make check-out a smooth process.  The guest will be reminded one day before they leave..
        /// </summary>
        public static string content_checkout_helptext {
            get {
                return ResourceManager.GetString("content_checkout_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave, departure, checkout.
        /// </summary>
        public static string content_checkout_keywords {
            get {
                return ResourceManager.GetString("content_checkout_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        public static string content_checkout_title {
            get {
                return ResourceManager.GetString("content_checkout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide specifics about the coffee maker to your guests like whether or not to bring filters and special instructions..
        /// </summary>
        public static string content_coffeemaker_helptext {
            get {
                return ResourceManager.GetString("content_coffeemaker_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitchen, coffee, expresso.
        /// </summary>
        public static string content_coffeemaker_keywords {
            get {
                return ResourceManager.GetString("content_coffeemaker_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Maker.
        /// </summary>
        public static string content_coffeemaker_title {
            get {
                return ResourceManager.GetString("content_coffeemaker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the guest your contact phone, email, etc. so they can get in touch with you before, during and after stay..
        /// </summary>
        public static string content_contactinfo_helptext {
            get {
                return ResourceManager.GetString("content_contactinfo_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact, owner, phone.
        /// </summary>
        public static string content_contactinfo_keywords {
            get {
                return ResourceManager.GetString("content_contactinfo_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string content_contactinfo_title {
            get {
                return ResourceManager.GetString("content_contactinfo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your area provide a grocery delivery service your guest might love to take advantage of?  If so let them know here..
        /// </summary>
        public static string content_delivery_helptext {
            get {
                return ResourceManager.GetString("content_delivery_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grocery, food, market.
        /// </summary>
        public static string content_delivery_keywords {
            get {
                return ResourceManager.GetString("content_delivery_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery Delivery.
        /// </summary>
        public static string content_delivery_title {
            get {
                return ResourceManager.GetString("content_delivery_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GPS map to your property will be provided automatically but sometimes it helps to have written directions as well..
        /// </summary>
        public static string content_drivingdirections_helptext {
            get {
                return ResourceManager.GetString("content_drivingdirections_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driving, directions.
        /// </summary>
        public static string content_drivingdirections_keywords {
            get {
                return ResourceManager.GetString("content_drivingdirections_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Directions.
        /// </summary>
        public static string content_drivingdirections_title {
            get {
                return ResourceManager.GetString("content_drivingdirections_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your rental includes electronic devices such as game systems, dvds, etc. that might need special instructions put them here..
        /// </summary>
        public static string content_electronics_helptext {
            get {
                return ResourceManager.GetString("content_electronics_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dvd, xbox, nintendo, wii, ps3, sony, video, stereo.
        /// </summary>
        public static string content_electronics_keywords {
            get {
                return ResourceManager.GetString("content_electronics_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string content_electronics_title {
            get {
                return ResourceManager.GetString("content_electronics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your rental requires an elevator to access it and they are special codes or instructions put them here..
        /// </summary>
        public static string content_elevator_helptext {
            get {
                return ResourceManager.GetString("content_elevator_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elevator, rules.
        /// </summary>
        public static string content_elevator_keywords {
            get {
                return ResourceManager.GetString("content_elevator_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevator.
        /// </summary>
        public static string content_elevator_title {
            get {
                return ResourceManager.GetString("content_elevator_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the event of an emergency provide your guest with anything that might be helpful in keeping them safe..
        /// </summary>
        public static string content_emergency_helptext {
            get {
                return ResourceManager.GetString("content_emergency_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to police, emergency, evacuate.
        /// </summary>
        public static string content_emergency_keywords {
            get {
                return ResourceManager.GetString("content_emergency_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string content_emergency_title {
            get {
                return ResourceManager.GetString("content_emergency_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are any details or pecularities your guests need to be aware of for final payments put those details here.
        /// </summary>
        public static string content_finalpayment_helptext {
            get {
                return ResourceManager.GetString("content_finalpayment_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment,money,final.
        /// </summary>
        public static string content_finalpayment_keywords {
            get {
                return ResourceManager.GetString("content_finalpayment_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Payment.
        /// </summary>
        public static string content_finalpayment_title {
            get {
                return ResourceManager.GetString("content_finalpayment_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_findmyrental_helptext {
            get {
                return ResourceManager.GetString("content_findmyrental_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map,directions,location,road,highway,find.
        /// </summary>
        public static string content_findmyrental_keywords {
            get {
                return ResourceManager.GetString("content_findmyrental_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find My Rental.
        /// </summary>
        public static string content_findmyrental_title {
            get {
                return ResourceManager.GetString("content_findmyrental_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let you guest know how to use any fireplace or fire pits in your rental.
        /// </summary>
        public static string content_fireplace_helptext {
            get {
                return ResourceManager.GetString("content_fireplace_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire, pit, wood, campfire.
        /// </summary>
        public static string content_fireplace_keywords {
            get {
                return ResourceManager.GetString("content_fireplace_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace/Fire Pit.
        /// </summary>
        public static string content_fireplace_title {
            get {
                return ResourceManager.GetString("content_fireplace_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guest information on fishing licenses, best spots to fish from etc..
        /// </summary>
        public static string content_fishing_helptext {
            get {
                return ResourceManager.GetString("content_fishing_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fish, boat.
        /// </summary>
        public static string content_fishing_keywords {
            get {
                return ResourceManager.GetString("content_fishing_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        public static string content_fishing_title {
            get {
                return ResourceManager.GetString("content_fishing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is a fitness center or fitness activities in the area let your guest know details on how to access it, etc..
        /// </summary>
        public static string content_fitness_helptext {
            get {
                return ResourceManager.GetString("content_fitness_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fitness, exercise, bike, run, walk.
        /// </summary>
        public static string content_fitness_keywords {
            get {
                return ResourceManager.GetString("content_fitness_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness/Fitness Center.
        /// </summary>
        public static string content_fitness_title {
            get {
                return ResourceManager.GetString("content_fitness_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you provide a golf cart or there rentals, etc in your area let your guests know..
        /// </summary>
        public static string content_golfcart_helptext {
            get {
                return ResourceManager.GetString("content_golfcart_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to golf.
        /// </summary>
        public static string content_golfcart_keywords {
            get {
                return ResourceManager.GetString("content_golfcart_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        public static string content_golfcart_title {
            get {
                return ResourceManager.GetString("content_golfcart_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your guests will be interested in grilling so let them know if there are any specifics to get the grill going or what not to do..
        /// </summary>
        public static string content_grilling_helptext {
            get {
                return ResourceManager.GetString("content_grilling_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grill, cook, fire.
        /// </summary>
        public static string content_grilling_keywords {
            get {
                return ResourceManager.GetString("content_grilling_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilling.
        /// </summary>
        public static string content_grilling_title {
            get {
                return ResourceManager.GetString("content_grilling_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guest with any specifics about the heater and air conditioner..
        /// </summary>
        public static string content_heatac_helptext {
            get {
                return ResourceManager.GetString("content_heatac_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heat, a/c, air conditioner.
        /// </summary>
        public static string content_heatac_keywords {
            get {
                return ResourceManager.GetString("content_heatac_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat &amp; A/C.
        /// </summary>
        public static string content_heatac_title {
            get {
                return ResourceManager.GetString("content_heatac_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a good place to list out any other tips your guest might enjoy in the area, etc..
        /// </summary>
        public static string content_helpfultips_helptext {
            get {
                return ResourceManager.GetString("content_helpfultips_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip, area, instructions.
        /// </summary>
        public static string content_helpfultips_keywords {
            get {
                return ResourceManager.GetString("content_helpfultips_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful Tips.
        /// </summary>
        public static string content_helpfultips_title {
            get {
                return ResourceManager.GetString("content_helpfultips_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your guests about hiking or trails in the area here.
        /// </summary>
        public static string content_hiking_helptext {
            get {
                return ResourceManager.GetString("content_hiking_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walk,exercise,outdoors,hiking,mountain.
        /// </summary>
        public static string content_hiking_keywords {
            get {
                return ResourceManager.GetString("content_hiking_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        public static string content_hiking_title {
            get {
                return ResourceManager.GetString("content_hiking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your rental has a land line attached to provide the phone number here so the guests can use it during their stay..
        /// </summary>
        public static string content_homephone_helptext {
            get {
                return ResourceManager.GetString("content_homephone_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home, phone, telephone.
        /// </summary>
        public static string content_homephone_keywords {
            get {
                return ResourceManager.GetString("content_homephone_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Telephone.
        /// </summary>
        public static string content_homephone_title {
            get {
                return ResourceManager.GetString("content_homephone_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a guest can request housekeeping service or there is something they need to know put that information here.
        /// </summary>
        public static string content_housekeeping_helptext {
            get {
                return ResourceManager.GetString("content_housekeeping_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clean,house,broom,pan.
        /// </summary>
        public static string content_housekeeping_keywords {
            get {
                return ResourceManager.GetString("content_housekeeping_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housekeeping.
        /// </summary>
        public static string content_housekeeping_title {
            get {
                return ResourceManager.GetString("content_housekeeping_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guest with any specifics rules you want them to adhere by regarding your rental..
        /// </summary>
        public static string content_houserules_helptext {
            get {
                return ResourceManager.GetString("content_houserules_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule, instructions.
        /// </summary>
        public static string content_houserules_keywords {
            get {
                return ResourceManager.GetString("content_houserules_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Rules.
        /// </summary>
        public static string content_houserules_title {
            get {
                return ResourceManager.GetString("content_houserules_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite others staying with you to get access to this information, etc.
        /// </summary>
        public static string content_inviteother_helptext {
            get {
                return ResourceManager.GetString("content_inviteother_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite, share, access, code.
        /// </summary>
        public static string content_inviteother_keywords {
            get {
                return ResourceManager.GetString("content_inviteother_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Others.
        /// </summary>
        public static string content_inviteother_title {
            get {
                return ResourceManager.GetString("content_inviteother_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide specifics about your kitchen to your guests if there is anything special they should know..
        /// </summary>
        public static string content_kitchen_helptext {
            get {
                return ResourceManager.GetString("content_kitchen_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitchen, oven, stove, microwave, dishwasher, freezer, refrigerator, ice.
        /// </summary>
        public static string content_kitchen_keywords {
            get {
                return ResourceManager.GetString("content_kitchen_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string content_kitchen_title {
            get {
                return ResourceManager.GetString("content_kitchen_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guest with any laundry details like how to operate washers and dryers, etc..
        /// </summary>
        public static string content_laundry_helptext {
            get {
                return ResourceManager.GetString("content_laundry_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to washer, dryer, dry cleaning.
        /// </summary>
        public static string content_laundry_keywords {
            get {
                return ResourceManager.GetString("content_laundry_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        public static string content_laundry_title {
            get {
                return ResourceManager.GetString("content_laundry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If anything goes wrong during your guests stay let them know the procedure on how to get things resolved.  This might include an alternate phone number, email, etc..
        /// </summary>
        public static string content_maintenance_helptext {
            get {
                return ResourceManager.GetString("content_maintenance_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fix, broken, maintenance.
        /// </summary>
        public static string content_maintenance_keywords {
            get {
                return ResourceManager.GetString("content_maintenance_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Issues.
        /// </summary>
        public static string content_maintenance_title {
            get {
                return ResourceManager.GetString("content_maintenance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a great place to put anything else that your guest might like.
        /// </summary>
        public static string content_misc_helptext {
            get {
                return ResourceManager.GetString("content_misc_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misc.
        /// </summary>
        public static string content_misc_keywords {
            get {
                return ResourceManager.GetString("content_misc_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string content_misc_title {
            get {
                return ResourceManager.GetString("content_misc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are specific noise ordinances in your area after certain times let your guest know here..
        /// </summary>
        public static string content_noisepolicy_helptext {
            get {
                return ResourceManager.GetString("content_noisepolicy_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noise, music, stereo.
        /// </summary>
        public static string content_noisepolicy_keywords {
            get {
                return ResourceManager.GetString("content_noisepolicy_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Policy.
        /// </summary>
        public static string content_noisepolicy_title {
            get {
                return ResourceManager.GetString("content_noisepolicy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there are specifics about parking at your rental provide them to the guest here.  This could include parking codes, etc..
        /// </summary>
        public static string content_parking_helptext {
            get {
                return ResourceManager.GetString("content_parking_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parking, car, rules, garage.
        /// </summary>
        public static string content_parking_keywords {
            get {
                return ResourceManager.GetString("content_parking_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string content_parking_title {
            get {
                return ResourceManager.GetString("content_parking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you allow pets or have any specific rules for pets provide them here..
        /// </summary>
        public static string content_pets_helptext {
            get {
                return ResourceManager.GetString("content_pets_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dog, cat, pet.
        /// </summary>
        public static string content_pets_keywords {
            get {
                return ResourceManager.GetString("content_pets_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        public static string content_pets_title {
            get {
                return ResourceManager.GetString("content_pets_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide specifics about the pool connected to your rental if you have one.  Also if you have a jacuzzi let your guests know how to operate it as well..
        /// </summary>
        public static string content_pool_helptext {
            get {
                return ResourceManager.GetString("content_pool_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swim, pool, water.
        /// </summary>
        public static string content_pool_keywords {
            get {
                return ResourceManager.GetString("content_pool_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool(s).
        /// </summary>
        public static string content_pool_title {
            get {
                return ResourceManager.GetString("content_pool_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your guests what to do on rainy days..
        /// </summary>
        public static string content_rainy_helptext {
            get {
                return ResourceManager.GetString("content_rainy_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain,weather.
        /// </summary>
        public static string content_rainy_keywords {
            get {
                return ResourceManager.GetString("content_rainy_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainy Days.
        /// </summary>
        public static string content_rainy_title {
            get {
                return ResourceManager.GetString("content_rainy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guests with any safety information about beaches, mountains, etc..
        /// </summary>
        public static string content_safety_helptext {
            get {
                return ResourceManager.GetString("content_safety_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to safety, emergency.
        /// </summary>
        public static string content_safety_keywords {
            get {
                return ResourceManager.GetString("content_safety_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        public static string content_safety_title {
            get {
                return ResourceManager.GetString("content_safety_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_signguestbook_helptext {
            get {
                return ResourceManager.GetString("content_signguestbook_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign, guestbook.
        /// </summary>
        public static string content_signguestbook_keywords {
            get {
                return ResourceManager.GetString("content_signguestbook_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Guestbook.
        /// </summary>
        public static string content_signguestbook_title {
            get {
                return ResourceManager.GetString("content_signguestbook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guest details on skiing options, etc..
        /// </summary>
        public static string content_skiing_helptext {
            get {
                return ResourceManager.GetString("content_skiing_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ski, lift, rental, tickets, mountain.
        /// </summary>
        public static string content_skiing_keywords {
            get {
                return ResourceManager.GetString("content_skiing_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiing.
        /// </summary>
        public static string content_skiing_title {
            get {
                return ResourceManager.GetString("content_skiing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any rules or notes on what a guest should do if they smoke provide them here..
        /// </summary>
        public static string content_smoking_helptext {
            get {
                return ResourceManager.GetString("content_smoking_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smoking, smoke, cigarettes, rules.
        /// </summary>
        public static string content_smoking_keywords {
            get {
                return ResourceManager.GetString("content_smoking_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        public static string content_smoking_title {
            get {
                return ResourceManager.GetString("content_smoking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a great place to tell your guests about what tennis options are offered in the area.
        /// </summary>
        public static string content_tennis_helptext {
            get {
                return ResourceManager.GetString("content_tennis_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tennis,sports.
        /// </summary>
        public static string content_tennis_keywords {
            get {
                return ResourceManager.GetString("content_tennis_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        public static string content_tennis_title {
            get {
                return ResourceManager.GetString("content_tennis_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_thankyou_helptext {
            get {
                return ResourceManager.GetString("content_thankyou_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanks, .
        /// </summary>
        public static string content_thankyou_keywords {
            get {
                return ResourceManager.GetString("content_thankyou_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string content_thankyou_title {
            get {
                return ResourceManager.GetString("content_thankyou_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your rentals are in areas where tides shift quite a bit provide links and details so your guests can view the tide charts..
        /// </summary>
        public static string content_tides_helptext {
            get {
                return ResourceManager.GetString("content_tides_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocean,water,tides,safety,moon.
        /// </summary>
        public static string content_tides_keywords {
            get {
                return ResourceManager.GetString("content_tides_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean Tides.
        /// </summary>
        public static string content_tides_title {
            get {
                return ResourceManager.GetString("content_tides_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there trolleys or other forms of transportation available to your guests?  Let them know here..
        /// </summary>
        public static string content_transportation_helptext {
            get {
                return ResourceManager.GetString("content_transportation_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transportation, bus, van, trolley.
        /// </summary>
        public static string content_transportation_keywords {
            get {
                return ResourceManager.GetString("content_transportation_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string content_transportation_title {
            get {
                return ResourceManager.GetString("content_transportation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let your guests know when trash will be picked up.  Pick the days below and a reminder will be set the night before reminding them..
        /// </summary>
        public static string content_trash_helptext {
            get {
                return ResourceManager.GetString("content_trash_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to garbage, trash, disposal.
        /// </summary>
        public static string content_trash_keywords {
            get {
                return ResourceManager.GetString("content_trash_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string content_trash_title {
            get {
                return ResourceManager.GetString("content_trash_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your guests instructions on using the TVs and provide links to cable station listings in your area..
        /// </summary>
        public static string content_tv_helptext {
            get {
                return ResourceManager.GetString("content_tv_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv, cable, hd, espn, hbo, satellite.
        /// </summary>
        public static string content_tv_keywords {
            get {
                return ResourceManager.GetString("content_tv_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV/Cable.
        /// </summary>
        public static string content_tv_title {
            get {
                return ResourceManager.GetString("content_tv_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_viewguestbook_helptext {
            get {
                return ResourceManager.GetString("content_viewguestbook_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guestbook.
        /// </summary>
        public static string content_viewguestbook_keywords {
            get {
                return ResourceManager.GetString("content_viewguestbook_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Guestbook.
        /// </summary>
        public static string content_viewguestbook_title {
            get {
                return ResourceManager.GetString("content_viewguestbook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string content_welcome_helptext {
            get {
                return ResourceManager.GetString("content_welcome_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome, intro, about, owner.
        /// </summary>
        public static string content_welcome_keywords {
            get {
                return ResourceManager.GetString("content_welcome_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string content_welcome_title {
            get {
                return ResourceManager.GetString("content_welcome_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a list of items such as towels, etc. that is provided with your rental to let the guest know before they get here..
        /// </summary>
        public static string content_whatsprovided_helptext {
            get {
                return ResourceManager.GetString("content_whatsprovided_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack, bring, provided.
        /// </summary>
        public static string content_whatsprovided_keywords {
            get {
                return ResourceManager.GetString("content_whatsprovided_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Provided.
        /// </summary>
        public static string content_whatsprovided_title {
            get {
                return ResourceManager.GetString("content_whatsprovided_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help your guests during their packing to make sure they bring necessary items from home that will enhance their stay..
        /// </summary>
        public static string content_whattopack_helptext {
            get {
                return ResourceManager.GetString("content_whattopack_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack, bring, included.
        /// </summary>
        public static string content_whattopack_keywords {
            get {
                return ResourceManager.GetString("content_whattopack_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What To Pack.
        /// </summary>
        public static string content_whattopack_title {
            get {
                return ResourceManager.GetString("content_whattopack_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide all the necessary information to your guests for accessing the internet.  Provide router name and passwords..
        /// </summary>
        public static string content_wifi_helptext {
            get {
                return ResourceManager.GetString("content_wifi_helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internet, wifi, router, broadband.
        /// </summary>
        public static string content_wifi_keywords {
            get {
                return ResourceManager.GetString("content_wifi_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIFI.
        /// </summary>
        public static string content_wifi_title {
            get {
                return ResourceManager.GetString("content_wifi_title", resourceCulture);
            }
        }
    }
}
