//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.Languages.LanguageStrings", typeof(LanguageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Danish {
            get {
                return ResourceManager.GetString("Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch_Netherlands {
            get {
                return ResourceManager.GetString("Dutch_Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (AUS).
        /// </summary>
        public static string English_Australia {
            get {
                return ResourceManager.GetString("English_Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (CA).
        /// </summary>
        public static string English_Canada {
            get {
                return ResourceManager.GetString("English_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (India).
        /// </summary>
        public static string English_India {
            get {
                return ResourceManager.GetString("English_India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string English_Ireland {
            get {
                return ResourceManager.GetString("English_Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (NZ).
        /// </summary>
        public static string English_NewZealand {
            get {
                return ResourceManager.GetString("English_NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (UK).
        /// </summary>
        public static string English_UK {
            get {
                return ResourceManager.GetString("English_UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English_US {
            get {
                return ResourceManager.GetString("English_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Finnish {
            get {
                return ResourceManager.GetString("Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (CA).
        /// </summary>
        public static string French_Canada {
            get {
                return ResourceManager.GetString("French_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French_France {
            get {
                return ResourceManager.GetString("French_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (AUS).
        /// </summary>
        public static string German_Austria {
            get {
                return ResourceManager.GetString("German_Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German_Germany {
            get {
                return ResourceManager.GetString("German_Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian_Italy {
            get {
                return ResourceManager.GetString("Italian_Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Norwegian_Norway {
            get {
                return ResourceManager.GetString("Norwegian_Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string Portuguese_Brazil {
            get {
                return ResourceManager.GetString("Portuguese_Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese_Portugal {
            get {
                return ResourceManager.GetString("Portuguese_Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian_Russia {
            get {
                return ResourceManager.GetString("Russian_Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (ARG).
        /// </summary>
        public static string Spanish_Argentina {
            get {
                return ResourceManager.GetString("Spanish_Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (COL).
        /// </summary>
        public static string Spanish_Columbia {
            get {
                return ResourceManager.GetString("Spanish_Columbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (MX).
        /// </summary>
        public static string Spanish_Mexico {
            get {
                return ResourceManager.GetString("Spanish_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish_Spain {
            get {
                return ResourceManager.GetString("Spanish_Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish_Sweden {
            get {
                return ResourceManager.GetString("Swedish_Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish_Turkey {
            get {
                return ResourceManager.GetString("Turkish_Turkey", resourceCulture);
            }
        }
    }
}
