//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.ActivityItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityItemStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityItemStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.ActivityItems.ActivityItemStrings", typeof(ActivityItemStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_called_category {
            get {
                return ResourceManager.GetString("activity_guest_called_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Called.
        /// </summary>
        public static string activity_guest_called_title {
            get {
                return ResourceManager.GetString("activity_guest_called_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_checkedin_category {
            get {
                return ResourceManager.GetString("activity_guest_checkedin_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Checked-In.
        /// </summary>
        public static string activity_guest_checkedin_title {
            get {
                return ResourceManager.GetString("activity_guest_checkedin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_checkedout_category {
            get {
                return ResourceManager.GetString("activity_guest_checkedout_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Checked-Out.
        /// </summary>
        public static string activity_guest_checkedout_title {
            get {
                return ResourceManager.GetString("activity_guest_checkedout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_contentrequested_category {
            get {
                return ResourceManager.GetString("activity_guest_contentrequested_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Requested Content.
        /// </summary>
        public static string activity_guest_contentrequested_title {
            get {
                return ResourceManager.GetString("activity_guest_contentrequested_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_emailed_category {
            get {
                return ResourceManager.GetString("activity_guest_emailed_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Emailed.
        /// </summary>
        public static string activity_guest_emailed_title {
            get {
                return ResourceManager.GetString("activity_guest_emailed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_feedback_category {
            get {
                return ResourceManager.GetString("activity_guest_feedback_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Left Feedback.
        /// </summary>
        public static string activity_guest_feedback_title {
            get {
                return ResourceManager.GetString("activity_guest_feedback_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_guestbook_category {
            get {
                return ResourceManager.GetString("activity_guest_guestbook_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Signed Guestbook.
        /// </summary>
        public static string activity_guest_guestbook_title {
            get {
                return ResourceManager.GetString("activity_guest_guestbook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_guestofguestinvited_category {
            get {
                return ResourceManager.GetString("activity_guest_guestofguestinvited_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest of Guest Invited.
        /// </summary>
        public static string activity_guest_guestofguestinvited_title {
            get {
                return ResourceManager.GetString("activity_guest_guestofguestinvited_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_guestofguestinvitedfollowup_category {
            get {
                return ResourceManager.GetString("activity_guest_guestofguestinvitedfollowup_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest of Guest Invited Followup.
        /// </summary>
        public static string activity_guest_guestofguestinvitedfollowup_title {
            get {
                return ResourceManager.GetString("activity_guest_guestofguestinvitedfollowup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_invited_category {
            get {
                return ResourceManager.GetString("activity_guest_invited_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Invited.
        /// </summary>
        public static string activity_guest_invited_title {
            get {
                return ResourceManager.GetString("activity_guest_invited_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_invitedfollowup_category {
            get {
                return ResourceManager.GetString("activity_guest_invitedfollowup_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Invited Followup.
        /// </summary>
        public static string activity_guest_invitedfollowup_title {
            get {
                return ResourceManager.GetString("activity_guest_invitedfollowup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_likedsuggestion_category {
            get {
                return ResourceManager.GetString("activity_guest_likedsuggestion_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Liked Suggestion.
        /// </summary>
        public static string activity_guest_likedsuggestion_title {
            get {
                return ResourceManager.GetString("activity_guest_likedsuggestion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_reminded_category {
            get {
                return ResourceManager.GetString("activity_guest_reminded_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Reminded About....
        /// </summary>
        public static string activity_guest_reminded_title {
            get {
                return ResourceManager.GetString("activity_guest_reminded_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_texted_category {
            get {
                return ResourceManager.GetString("activity_guest_texted_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Texted.
        /// </summary>
        public static string activity_guest_texted_title {
            get {
                return ResourceManager.GetString("activity_guest_texted_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_thanked_category {
            get {
                return ResourceManager.GetString("activity_guest_thanked_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Thanked.
        /// </summary>
        public static string activity_guest_thanked_title {
            get {
                return ResourceManager.GetString("activity_guest_thanked_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_usingapp_category {
            get {
                return ResourceManager.GetString("activity_guest_usingapp_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Using App.
        /// </summary>
        public static string activity_guest_usingapp_title {
            get {
                return ResourceManager.GetString("activity_guest_usingapp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Activity.
        /// </summary>
        public static string activity_guest_usingweb_category {
            get {
                return ResourceManager.GetString("activity_guest_usingweb_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Using Web.
        /// </summary>
        public static string activity_guest_usingweb_title {
            get {
                return ResourceManager.GetString("activity_guest_usingweb_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string activity_guest_welcomed_category {
            get {
                return ResourceManager.GetString("activity_guest_welcomed_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Welcomed.
        /// </summary>
        public static string activity_guest_welcomed_title {
            get {
                return ResourceManager.GetString("activity_guest_welcomed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad To Have You.
        /// </summary>
        public static string system_housecleaner_finished_category {
            get {
                return ResourceManager.GetString("system_housecleaner_finished_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Cleaner Finished.
        /// </summary>
        public static string system_housecleaner_finished_title {
            get {
                return ResourceManager.GetString("system_housecleaner_finished_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad To Have You.
        /// </summary>
        public static string system_housecleaner_notified_category {
            get {
                return ResourceManager.GetString("system_housecleaner_notified_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Cleaner Notified.
        /// </summary>
        public static string system_housecleaner_notified_title {
            get {
                return ResourceManager.GetString("system_housecleaner_notified_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad To Have You.
        /// </summary>
        public static string system_owner_emailneedsconfirmation_category {
            get {
                return ResourceManager.GetString("system_owner_emailneedsconfirmation_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Needs Confirmation.
        /// </summary>
        public static string system_owner_emailneedsconfirmation_title {
            get {
                return ResourceManager.GetString("system_owner_emailneedsconfirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad To Have You.
        /// </summary>
        public static string system_owner_owneringraceperiod_category {
            get {
                return ResourceManager.GetString("system_owner_owneringraceperiod_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        public static string system_owner_owneringraceperiod_title {
            get {
                return ResourceManager.GetString("system_owner_owneringraceperiod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string system_owner_referothers_category {
            get {
                return ResourceManager.GetString("system_owner_referothers_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer Other Owners.
        /// </summary>
        public static string system_owner_referothers_title {
            get {
                return ResourceManager.GetString("system_owner_referothers_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string system_owner_tip_category {
            get {
                return ResourceManager.GetString("system_owner_tip_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string system_owner_tip_title {
            get {
                return ResourceManager.GetString("system_owner_tip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string system_owner_unitrequiresattention_category {
            get {
                return ResourceManager.GetString("system_owner_unitrequiresattention_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Unit Needs Attention.
        /// </summary>
        public static string system_owner_unitrequiresattention_title {
            get {
                return ResourceManager.GetString("system_owner_unitrequiresattention_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Activity.
        /// </summary>
        public static string system_owner_upcomingreservation_category {
            get {
                return ResourceManager.GetString("system_owner_upcomingreservation_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Reservation.
        /// </summary>
        public static string system_owner_upcomingreservation_title {
            get {
                return ResourceManager.GetString("system_owner_upcomingreservation_title", resourceCulture);
            }
        }
    }
}
