//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.EmailContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailContentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.EmailContent.EmailContentStrings", typeof(EmailContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) requested (Content.Description).  Please add this content to ensure your rental information is up to date.&lt;/p&gt;
        ///&lt;p&gt;You only have to provide this information one time and  it will be available to future guests. &lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_ContentRequested_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_ContentRequested_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your information for this and future guests.
        /// </summary>
        public static string Owner_Guest_ContentRequested_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_ContentRequested_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Content.Title).
        /// </summary>
        public static string Owner_Guest_ContentRequested_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_ContentRequested_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your guests the information they need.
        /// </summary>
        public static string Owner_Guest_ContentRequested_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_ContentRequested_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner_Guest_Feedback_Content.
        /// </summary>
        public static string Owner_Guest_Feedback_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_Feedback_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner_Guest_Feedback_PreHeader.
        /// </summary>
        public static string Owner_Guest_Feedback_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_Feedback_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner_Guest_Feedback_Subject.
        /// </summary>
        public static string Owner_Guest_Feedback_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_Feedback_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner_Guest_Feedback_Title.
        /// </summary>
        public static string Owner_Guest_Feedback_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_Feedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) or someone in their party has submitted a review of your property. We are currently ensuring it meets our content guidelines before posting it for others to see.&lt;/p&gt;
        ///&lt;p&gt;(Guest.FirstName) or someone in their party has submitted a review of your property. We are currently ensuring it meets our content guidelines before posting it for others to see.&lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_Guestbook_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_Guestbook_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be posting it to your Mobile Hospitality Manager soon.
        /// </summary>
        public static string Owner_Guest_Guestbook_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_Guestbook_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A review has been submitted about the (Guest.LastName) stay.
        /// </summary>
        public static string Owner_Guest_Guestbook_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_Guestbook_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve received a new review.
        /// </summary>
        public static string Owner_Guest_Guestbook_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_Guestbook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(HostGuest.FullName) has invited another person to access your Mobile Hospitality Manager. Guests can share information about your property and the details of their stay with friends and family traveling with them. &lt;/p&gt;
        ///&lt;p&gt;Their information is below. Have a great day!&lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your guest has been re-invited to access the Mobile Hospitality Manager. If you would like to manage this stay or ensure you provided access visit the My Guests tab.&lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Followup_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Followup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your upcoming guest has not yet viewed your hospitality content.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Followup_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Followup_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (HostGuest.FullName) guest has received a reminder.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Followup_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Followup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve reminded (HostGuest.FirstName)’s guest about your hospitality information.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Followup_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others have been invited to your Mobile Hospitality Manager.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See reviews.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_SeeReviews {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_SeeReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (HostGuest.FullName) has shared your hospitality information.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hospitality information has been shared.
        /// </summary>
        public static string Owner_Guest_GuestOfGuestInvited_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_GuestOfGuestInvited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) has downloaded the app and recently logged into the Mobile Hospitality Manager.
        ///                                                                  If you haven’t already, now’s the time to enter useful property information they might need. This will ensure your guests have the best stay possible. Once you’ve updated the content, it will be available to all your guests, so you only have to do it once!
        ///                                                              &lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_UsingApp_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingApp_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you’ve entered your rental information.
        /// </summary>
        public static string Owner_Guest_UsingApp_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingApp_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName) has accessed your info in our mobile app.
        /// </summary>
        public static string Owner_Guest_UsingApp_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingApp_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName) (Guest.LastName) has accessed your Mobile Hospitality information.
        /// </summary>
        public static string Owner_Guest_UsingApp_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) has recently logged into the Mobile Hospitality Manager. If you haven’t already, now’s the time to enter useful property information they might need. This will ensure your guests have the best stay possible. Once you’ve updated the content, it will be available to all your guests, so you only have to do it once!
        ///&lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_UsingWeb_Content {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingWeb_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) has recently logged into the Mobile Hospitality Manager. If you are satisfied with the content you have provided for your guests, no action is required. If you prefer not to receive these notifications moving forward, you can control them in the Settings tab.&lt;/p&gt;.
        /// </summary>
        public static string Owner_Guest_UsingWeb_Content_Engaged {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingWeb_Content_Engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you’ve entered your rental information.
        /// </summary>
        public static string Owner_Guest_UsingWeb_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingWeb_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName) has accessed your hospitality info.
        /// </summary>
        public static string Owner_Guest_UsingWeb_Subject {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingWeb_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName)  has accessed your Mobile Hospitality information.
        /// </summary>
        public static string Owner_Guest_UsingWeb_Title {
            get {
                return ResourceManager.GetString("Owner_Guest_UsingWeb_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You now have access to the HomeAway Mobile Hospitality Manager..
        /// </summary>
        public static string Owner_Onboard_Content {
            get {
                return ResourceManager.GetString("Owner_Onboard_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Mobile Hospitality Manager puts useful information about your property right into your guests’ hands through a mobile website or the HomeAway mobile app.
        ///                                                                                                        &lt;/p&gt;
        ///&lt;p&gt;Here’s how it works: once a guest books your vacation home, we’ll invite them to get the app or go to the mobile site so they can access the helpful tips you’ve provided, like check-in instructions, directions to your rental, and local r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Owner_Onboard_Content_Section1_Content {
            get {
                return ResourceManager.GetString("Owner_Onboard_Content_Section1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your guests&apos; stay by adding information.
        /// </summary>
        public static string Owner_Onboard_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Onboard_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your guests the information they need... right when they need it.
        /// </summary>
        public static string Owner_Onboard_Title {
            get {
                return ResourceManager.GetString("Owner_Onboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                                                    (Guest.FirstName)’s stay at your vacation home begins in a few days. If you have not done so already, there are two things you need to do to ensure your traveler can access the rental and starts off their trip on a good note:
        ///
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Content {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons, guests cannot view your property’s access information until you approve it. Click “Allow” in the “Pre-Arrival” information of the “My Guests” tab.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Content_Section1_Content {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Content_Section1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Unlock your rental access information.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Content_Section1_Title {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Content_Section1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to giving them the ability to access your property, you can add suggestions about where they can eat, get groceries, etc..
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Content_Section2_Content {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Content_Section2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Add useful information about your property.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Content_Section2_Title {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Content_Section2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you‘ve unlocked your rental access information.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_PreHeader {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName) arrives in three days.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Subject {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your guests the information they need before their stay.
        /// </summary>
        public static string Owner_Owner_UpcomingReservation_Title {
            get {
                return ResourceManager.GetString("Owner_Owner_UpcomingReservation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Your guest has been invited to access the Mobile Hospitality Manager. If you would like to re-invite this guest or add other guests to the stay visit the My Guests tab.&lt;/p&gt;
        ///&lt;p&gt;Their information is below. Have a great day!&lt;/p&gt;.
        /// </summary>
        public static string Owner_System_GuestInvited_Content {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your guest has been re-invited to access the Mobile Hospitality Manager. If you would like to manage this stay or ensure you provided access visit the My Guests tab.&lt;/p&gt;.
        /// </summary>
        public static string Owner_System_GuestInvited_Followup_Content {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Followup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName) has not yet accessed your hospitality info yet.
        /// </summary>
        public static string Owner_System_GuestInvited_Followup_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Followup_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName) (Guest.LastName) has been reminded to access Mobile Hospitality Manager.
        /// </summary>
        public static string Owner_System_GuestInvited_Followup_Subject {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Followup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve reminded your guest about your hospitality information.
        /// </summary>
        public static string Owner_System_GuestInvited_Followup_Title {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure your guests can take information about your property with them.
        /// </summary>
        public static string Owner_System_GuestInvited_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName) has been invited to your hospitality information.
        /// </summary>
        public static string Owner_System_GuestInvited_Subject {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hospitality information has been shared.
        /// </summary>
        public static string Owner_System_GuestInvited_Title {
            get {
                return ResourceManager.GetString("Owner_System_GuestInvited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You now have access to the HomeAway Mobile Hospitality Manager..
        /// </summary>
        public static string Owner_System_OnBoard_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Mobile Hospitality Manager puts useful information about your property right into your guests’ hands through a mobile website or the HomeAway mobile app. &lt;/p&gt;
        ///&lt;p&gt;Just after they book your guests are excited to find out all the fun things to do around your vacation home and to start planning their trip. They will be invited to access the app or mobile site so they can access local recommendations you’ve provided and check-in instructions, and directions to your rental.&lt;/p&gt;.
        /// </summary>
        public static string Owner_System_OnBoard_Content_Section1_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content_Section1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Mobile Hospitality Manager?.
        /// </summary>
        public static string Owner_System_OnBoard_Content_Section1_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content_Section1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                                                            Starting on &lt;b&gt;(Owner.GracePeriodExpiration)&lt;/b&gt;, your future guests will be invited to access information about their upcoming stay with you. They can also access it online.
        ///                                                                        &lt;/p&gt;
        ///&lt;p&gt;Login to the Mobile Hospitality Manager to provide helpful information to make their stay a great one. Once you’ve entered the content your future guests will be able to acce [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Owner_System_OnBoard_Content_Section2_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content_Section2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you need to do?.
        /// </summary>
        public static string Owner_System_OnBoard_Content_Section2_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content_Section2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                                                                            &lt;li&gt;Add helpful information such as directions and nearby points of interest&lt;/li&gt;
        ///                                                                            &lt;li&gt;Provide details like access codes and Wi-Fi passwords (think about the things you get asked for over and over again)&lt;/li&gt;
        ///                                                                            &lt;li&gt;Customize your welcome and thank you messages&lt;/li&gt;
        ///
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Owner_System_OnBoard_Content_Section3_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Content_Section3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a few days, your guests will be invited to the Mobile Hospitality Manager. If you have not already, take a moment to update your information before they see it!.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                                                Starting on &lt;b&gt;(Owner.GracePeriodExpiration)&lt;/b&gt;, your guests will be invited access information about their upcoming stay at your property. Just after they book your guests are excited to find out all the fun things to do around your vacation home and to start planning their trip.  Add content to the Mobile Hospitality Manager so they can find everything they need to make their stay a great one. Once you have provided the content your fut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section1_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you need to do?.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section1_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                                                                &lt;li&gt;Add helpful information such as directions and nearby points of interest&lt;/li&gt;
        ///                                                                &lt;li&gt;Provide details like access codes and Wi-Fi passwords (think about the things you get asked for over and over again)&lt;/li&gt;
        ///                                                                &lt;li&gt;Customize your welcome and thank you messages&lt;/li&gt;
        ///
        ///                                               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section2_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You can always access your Mobile Hospitality Manager through the “Hospitality” link in your dashboard. &lt;/p&gt;.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section3_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To activate the experience for your guests before (Owner.GracePeriodExpiration), select the “My Guests” tab in the “Hospitality” section and click the “Invite guests” button..
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section4_Content {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to activate your mobile experience sooner?.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section4_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how Lianna is using Mobile Hospitality Manager to give her guests a great experience.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section5_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about the Mobile Hospitality Manager.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Content_Section6_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Content_Section6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have two more days to update your property information.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your hospitality content before guests can see it.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Subject {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your guests the information they need... right when they need it.
        /// </summary>
        public static string Owner_System_OnBoard_Followup_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your guests excited for their trip just after they book.
        /// </summary>
        public static string Owner_System_OnBoard_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Mobile Hospitality Manager.
        /// </summary>
        public static string Owner_System_OnBoard_Subject {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your guests the information they need... right when they need it.
        /// </summary>
        public static string Owner_System_OnBoard_Title {
            get {
                return ResourceManager.GetString("Owner_System_OnBoard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; (Guest.FirstName) was reminded about (Content.Description). &lt;br/&gt; Their information is below. Have a great day!&lt;/p&gt;.
        /// </summary>
        public static string Owner_System_Reminded_Content {
            get {
                return ResourceManager.GetString("Owner_System_Reminded_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve sent your guest a reminder about content you provided.
        /// </summary>
        public static string Owner_System_Reminded_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_Reminded_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName) was reminded about (Content.Description).
        /// </summary>
        public static string Owner_System_Reminded_Subject {
            get {
                return ResourceManager.GetString("Owner_System_Reminded_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Content.Title).
        /// </summary>
        public static string Owner_System_Reminded_Title {
            get {
                return ResourceManager.GetString("Owner_System_Reminded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since your guest, (Guest.FirstName), is checking out today we delivered a thank you message. &lt;br/&gt; If you would like to customize the Thank You message your guest receives for future guests, visit the My Rental tab to do so..
        /// </summary>
        public static string Owner_System_Thanked_Content {
            get {
                return ResourceManager.GetString("Owner_System_Thanked_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve sent a thank you email on your behalf.
        /// </summary>
        public static string Owner_System_Thanked_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_Thanked_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FullName), has been thanked.
        /// </summary>
        public static string Owner_System_Thanked_Subject {
            get {
                return ResourceManager.GetString("Owner_System_Thanked_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your guest has been thanked for staying with you.
        /// </summary>
        public static string Owner_System_Thanked_Title {
            get {
                return ResourceManager.GetString("Owner_System_Thanked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;(Guest.FirstName) will be at your vacation home shortly. If you haven’t already, you should unlock your rental access information so that they will know how to access your property. Be sure to include other useful pre-arrival details like driving directions and check-in instructions.&lt;/p&gt;.
        /// </summary>
        public static string Owner_System_Welcomed_Content {
            get {
                return ResourceManager.GetString("Owner_System_Welcomed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve sent information about their upcoming stay.
        /// </summary>
        public static string Owner_System_Welcomed_PreHeader {
            get {
                return ResourceManager.GetString("Owner_System_Welcomed_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName) has received a welcome email.
        /// </summary>
        public static string Owner_System_Welcomed_Subject {
            get {
                return ResourceManager.GetString("Owner_System_Welcomed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A welcome email has been sent to your guest.
        /// </summary>
        public static string Owner_System_Welcomed_Title {
            get {
                return ResourceManager.GetString("Owner_System_Welcomed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your rental.
        /// </summary>
        public static string Shared_AccessYourRental {
            get {
                return ResourceManager.GetString("Shared_AccessYourRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your information now.
        /// </summary>
        public static string Shared_AddYourInformation {
            get {
                return ResourceManager.GetString("Shared_AddYourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date.
        /// </summary>
        public static string Shared_CheckInDate {
            get {
                return ResourceManager.GetString("Shared_CheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        public static string Shared_CheckOutDate {
            get {
                return ResourceManager.GetString("Shared_CheckOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Shared_EmailAddress {
            get {
                return ResourceManager.GetString("Shared_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest email.
        /// </summary>
        public static string Shared_GuestEmail {
            get {
                return ResourceManager.GetString("Shared_GuestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest name.
        /// </summary>
        public static string Shared_GuestName {
            get {
                return ResourceManager.GetString("Shared_GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest phone.
        /// </summary>
        public static string Shared_GuestPhone {
            get {
                return ResourceManager.GetString("Shared_GuestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage this stay.
        /// </summary>
        public static string Shared_ManageThisStay {
            get {
                return ResourceManager.GetString("Shared_ManageThisStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile invitation code.
        /// </summary>
        public static string Shared_MobileInvitationCode {
            get {
                return ResourceManager.GetString("Shared_MobileInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental name.
        /// </summary>
        public static string Shared_RentalName {
            get {
                return ResourceManager.GetString("Shared_RentalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation details.
        /// </summary>
        public static string Shared_ReservationDetails {
            get {
                return ResourceManager.GetString("Shared_ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take me there.
        /// </summary>
        public static string Shared_TakeMeThere {
            get {
                return ResourceManager.GetString("Shared_TakeMeThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                                                    &lt;b&gt;(HostGuest.FullName)&lt;/b&gt; has shared information about your vacation rental on (Brand.Name), and you can access it online, whenever you need it.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Whether you’re on a smartphone, tablet, or computer, you can click below to see everything you need to know about your &lt;b&gt;(Rental.City)&lt;/b&gt; vacation, arrival information and directions, as well as recommendations on which restaurants, activities, and events to check out during your stay.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Content_Section1 {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Content_Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;(HostGuest.FullName)&lt;/b&gt; recently shared details about your (Brand.Name) vacation home. That information is still waiting for you.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Followup_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Followup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Click below to see everything you need to know about your &lt;b&gt;(Rental.City)&lt;/b&gt; rental. Whether you’re on your computer, smartphone, or tablet, everything you need is there when you need it – your reservation, arrival information, and directions, as well as recommendations on which restaurants, activities, and events to check out during your stay.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Followup_Content_Section1 {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Followup_Content_Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t miss out on important rental informatio.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Followup_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Followup_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName)  - (HostGuest.FirstName) has shared rental information with you.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Followup_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Followup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to know…
        ///right when you need it.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Followup_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily access useful property information.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (HostGuest.FullName) has shared rental access information with you.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to know…
        ///right when you need it.
        /// </summary>
        public static string Traveler_Guest_GuestOfGuestInvite_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_GuestOfGuestInvite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations on booking a (Brand.Name) vacation home. To make your upcoming stay even more convenient, all the information you need about your rental is online, so you can access it whenever you need it..
        /// </summary>
        public static string Traveler_Guest_Invite_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Whether you’re on a smartphone, tablet, or computer, you can click below to see everything you need to know about your &lt;b&gt;(Rental.City)&lt;/b&gt; vacation, arrival information, and directions, as well as recommendations on which restaurants, activities, and events to check out during your stay.&lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_Invite_Content_Section1 {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Content_Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Brand.Name) is part of the HomeAway family and the HomeAway mobile app will support your stay..
        /// </summary>
        public static string Traveler_Guest_Invite_Content_Section2 {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Content_Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You recently booked a vacation home on (Brand.Name). Now’s the time to start thinking about the things you’re going to do while you’re there.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_Invite_Followup_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Followup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Whether you’re on a smartphone, tablet, or computer, you can click below to see everything you need to know about your (Rental.Region) vacation, arrival information, and directions, as well as recommendations on which restaurants, activities, and events to check out during your stay.
        ///                                                                &lt;/p&gt;.
        /// </summary>
        public static string Traveler_Guest_Invite_Followup_Content_Section1 {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Followup_Content_Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick and easy access to important info about your upcoming stay.
        /// </summary>
        public static string Traveler_Guest_Invite_Followup_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Followup_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName), your (Rental.City) vacation is just around the corner.
        /// </summary>
        public static string Traveler_Guest_Invite_Followup_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Followup_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property information in the palm of your hand.
        /// </summary>
        public static string Traveler_Guest_Invite_Followup_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access info about your upcoming stay.
        /// </summary>
        public static string Traveler_Guest_Invite_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Upcoming Stay In (Rental.City), (Rental.Region).
        /// </summary>
        public static string Traveler_Guest_Invite_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to know…  right when you need it.
        /// </summary>
        public static string Traveler_Guest_Invite_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_Invite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName), &lt;br/&gt; (Content.Description).
        /// </summary>
        public static string Traveler_Guest_Thankyou_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_Thankyou_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you had a great time in (Rental.City).
        /// </summary>
        public static string Traveler_Guest_Thankyou_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_Thankyou_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you so much for staying with us!.
        /// </summary>
        public static string Traveler_Guest_Thankyou_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_Thankyou_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was great having you.
        /// </summary>
        public static string Traveler_Guest_Thankyou_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_Thankyou_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest.FirstName), &lt;br/&gt;(Content.Description).
        /// </summary>
        public static string Traveler_Guest_Welcome_Content {
            get {
                return ResourceManager.GetString("Traveler_Guest_Welcome_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check property details to make sure you’re prepared for your upcoming stay.
        /// </summary>
        public static string Traveler_Guest_Welcome_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_Guest_Welcome_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your (Rental.Region) rental.
        /// </summary>
        public static string Traveler_Guest_Welcome_Subject {
            get {
                return ResourceManager.GetString("Traveler_Guest_Welcome_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about your (Brand.Name) rental… right when you need it.
        /// </summary>
        public static string Traveler_Guest_Welcome_Title {
            get {
                return ResourceManager.GetString("Traveler_Guest_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Congratulations on booking a &lt;b&gt;(Brand.Name)&lt;/b&gt; vacation home. To make your upcoming stay even more convenient, all the information you need about your rental is online, so you can access it whenever you need it.&lt;/p&gt;.
        /// </summary>
        public static string Traveler_PrimaryInvite_Content {
            get {
                return ResourceManager.GetString("Traveler_PrimaryInvite_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access info about your upcoming stay.
        /// </summary>
        public static string Traveler_PrimaryInvite_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_PrimaryInvite_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you’re on a smartphone, tablet, or computer, you can click below to see everything you need to know about your &lt;b&gt;(Rental.City)&lt;/b&gt; vacation, arrival information, and directions, as well as recommendations on which restaurants, activities, and events to check out during your stay..
        /// </summary>
        public static string Traveler_PrimaryInvite_Section1_Content {
            get {
                return ResourceManager.GetString("Traveler_PrimaryInvite_Section1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome (Guest.FirstName).
        /// </summary>
        public static string Traveler_PrimaryInvite_Title {
            get {
                return ResourceManager.GetString("Traveler_PrimaryInvite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Content.Description).
        /// </summary>
        public static string Traveler_System_Content_Content {
            get {
                return ResourceManager.GetString("Traveler_System_Content_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about (Rental.Name).
        /// </summary>
        public static string Traveler_System_Content_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_System_Content_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timely info about your rental..
        /// </summary>
        public static string Traveler_System_Content_Subject {
            get {
                return ResourceManager.GetString("Traveler_System_Content_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Content.Title).
        /// </summary>
        public static string Traveler_System_Content_Title {
            get {
                return ResourceManager.GetString("Traveler_System_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Every vacation must come to an end, and your stay is almost over. But before you get back to the hustle and bustle of your everyday life, take a few minutes and let us know how you enjoyed your time at (Rental.Name).
        ///                                                                &lt;/p&gt;
        ///&lt;p&gt;Click below to let the owner or property manager know how you enjoyed their vacation home. It just takes a minute.&lt;/p&gt;.
        /// </summary>
        public static string Traveler_System_SignGuestbook_Content {
            get {
                return ResourceManager.GetString("Traveler_System_SignGuestbook_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review about your vacation rental.
        /// </summary>
        public static string Traveler_System_SignGuestbook_PreHeader {
            get {
                return ResourceManager.GetString("Traveler_System_SignGuestbook_PreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a review.
        /// </summary>
        public static string Traveler_System_SignGuestbook_Subject {
            get {
                return ResourceManager.GetString("Traveler_System_SignGuestbook_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was your stay?.
        /// </summary>
        public static string Traveler_System_SignGuestbook_Title {
            get {
                return ResourceManager.GetString("Traveler_System_SignGuestbook_Title", resourceCulture);
            }
        }
    }
}
