//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.Portal.PortalStrings", typeof(PortalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string Integration_Invited {
            get {
                return ResourceManager.GetString("Integration_Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Guests.
        /// </summary>
        public static string Integration_MoreThanOneGuest {
            get {
                return ResourceManager.GetString("Integration_MoreThanOneGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Integration_NotFound {
            get {
                return ResourceManager.GetString("Integration_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Guest.
        /// </summary>
        public static string Integration_SingleGuest {
            get {
                return ResourceManager.GetString("Integration_SingleGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need First Name.
        /// </summary>
        public static string NeedFirst {
            get {
                return ResourceManager.GetString("NeedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Last Names.
        /// </summary>
        public static string NeedLast {
            get {
                return ResourceManager.GetString("NeedLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string Review_Anonymous {
            get {
                return ResourceManager.GetString("Review_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Store_Add {
            get {
                return ResourceManager.GetString("Store_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error activating this store item.  Please contact support..
        /// </summary>
        public static string Store_AddError {
            get {
                return ResourceManager.GetString("Store_AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string Store_HowItWorks {
            get {
                return ResourceManager.GetString("Store_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string Store_MoreInformation {
            get {
                return ResourceManager.GetString("Store_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Store_Remove {
            get {
                return ResourceManager.GetString("Store_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string Store_Screenshots {
            get {
                return ResourceManager.GetString("Store_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Store_Settings {
            get {
                return ResourceManager.GetString("Store_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added from HomeAway calendar.
        /// </summary>
        public static string Synchronized {
            get {
                return ResourceManager.GetString("Synchronized", resourceCulture);
            }
        }
    }
}
