//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.MyGuestsExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyGuestsExportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyGuestsExportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.MyGuestsExport.MyGuestsExportStrings", typeof(MyGuestsExportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string ColumnHeaderCheckin {
            get {
                return ResourceManager.GetString("ColumnHeaderCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string ColumnHeaderCheckOut {
            get {
                return ResourceManager.GetString("ColumnHeaderCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Email.
        /// </summary>
        public static string ColumnHeaderGuestEmail {
            get {
                return ResourceManager.GetString("ColumnHeaderGuestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest First Name.
        /// </summary>
        public static string ColumnHeaderGuestFirstName {
            get {
                return ResourceManager.GetString("ColumnHeaderGuestFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Last Name.
        /// </summary>
        public static string ColumnHeaderGuestLastName {
            get {
                return ResourceManager.GetString("ColumnHeaderGuestLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Phone.
        /// </summary>
        public static string ColumnHeaderGuestPhone {
            get {
                return ResourceManager.GetString("ColumnHeaderGuestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Name.
        /// </summary>
        public static string ColumnHeaderGuestRentalName {
            get {
                return ResourceManager.GetString("ColumnHeaderGuestRentalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnHeaderStatus {
            get {
                return ResourceManager.GetString("ColumnHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Holder.
        /// </summary>
        public static string ReservationHolder {
            get {
                return ResourceManager.GetString("ReservationHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited By: {0} {1}.
        /// </summary>
        public static string ReservationInvitedBy {
            get {
                return ResourceManager.GetString("ReservationInvitedBy", resourceCulture);
            }
        }
    }
}
