//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.Activity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.Activity.ActivityStrings", typeof(ActivityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Preview.
        /// </summary>
        public static string GPRV {
            get {
                return ResourceManager.GetString("GPRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string LTRL {
            get {
                return ResourceManager.GetString("LTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string NAVG {
            get {
                return ResourceManager.GetString("NAVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no content about WIFI, what to pack, when to arrive, etc.  This is your chance to let your guest know everything about your unit, arrival information, etc..
        /// </summary>
        public static string NCNT {
            get {
                return ResourceManager.GetString("NCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feedback was provided.
        /// </summary>
        public static string NoFeedback {
            get {
                return ResourceManager.GetString("NoFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notes.
        /// </summary>
        public static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no restaurant, bar, activity, etc. suggestions.  Help your guest become experts in your area so they have a great time at your rental..
        /// </summary>
        public static string NSGT {
            get {
                return ResourceManager.GetString("NSGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no thank you message.  Let your guests know how much you appreciate them staying with you..
        /// </summary>
        public static string NTKM {
            get {
                return ResourceManager.GetString("NTKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no welcome message.  We recommend you do this as it makes your guests feel more welcome.
        /// </summary>
        public static string NWLM {
            get {
                return ResourceManager.GetString("NWLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        public static string OGPD {
            get {
                return ResourceManager.GetString("OGPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New mobile hospitality activity: {0}.
        /// </summary>
        public static string OwnerSubject {
            get {
                return ResourceManager.GetString("OwnerSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.  Reservation is from {1} to {2}.
        /// </summary>
        public static string RMDS {
            get {
                return ResourceManager.GetString("RMDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is for {0} through {1}.  
        ///Notes: {2}.
        /// </summary>
        public static string RSVN {
            get {
                return ResourceManager.GetString("RSVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is for {0} through {1}.
        /// </summary>
        public static string RSVS {
            get {
                return ResourceManager.GetString("RSVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Review.
        /// </summary>
        public static string SignOurGuestbook {
            get {
                return ResourceManager.GetString("SignOurGuestbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave a review before you leave!.
        /// </summary>
        public static string SignOurGuestbookMessage {
            get {
                return ResourceManager.GetString("SignOurGuestbookMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Feedback.
        /// </summary>
        public static string VFBK {
            get {
                return ResourceManager.GetString("VFBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Review.
        /// </summary>
        public static string VGBK {
            get {
                return ResourceManager.GetString("VGBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reservation.
        /// </summary>
        public static string VRSV {
            get {
                return ResourceManager.GetString("VRSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
