//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.MobileView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobileViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.MobileView.MobileViewStrings", typeof(MobileViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access rental.
        /// </summary>
        public static string access_rental {
            get {
                return ResourceManager.GetString("access_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take advantage of recommendations.
        /// </summary>
        public static string advantage_recommendations {
            get {
                return ResourceManager.GetString("advantage_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In Date.
        /// </summary>
        public static string check_in_date {
            get {
                return ResourceManager.GetString("check_in_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string check_in_date_required_message {
            get {
                return ResourceManager.GetString("check_in_date_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address should be less than 256 characters.
        /// </summary>
        public static string email_maxlength_message {
            get {
                return ResourceManager.GetString("email_maxlength_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required.
        /// </summary>
        public static string email_required_message {
            get {
                return ResourceManager.GetString("email_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string experience_hidden {
            get {
                return ResourceManager.GetString("experience_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience is required.
        /// </summary>
        public static string experience_hidden_required_message {
            get {
                return ResourceManager.GetString("experience_hidden_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Your Reservation....
        /// </summary>
        public static string finding_your_reservation {
            get {
                return ResourceManager.GetString("finding_your_reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name should be less than 50 characters.
        /// </summary>
        public static string first_name_maxlength_message {
            get {
                return ResourceManager.GetString("first_name_maxlength_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string first_name_required_message {
            get {
                return ResourceManager.GetString("first_name_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From camera.
        /// </summary>
        public static string from_camera {
            get {
                return ResourceManager.GetString("from_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From photo library.
        /// </summary>
        public static string from_photo_library {
            get {
                return ResourceManager.GetString("from_photo_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the app!.
        /// </summary>
        public static string get_the_app {
            get {
                return ResourceManager.GetString("get_the_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string i_agree_to {
            get {
                return ResourceManager.GetString("i_agree_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Other Guests.
        /// </summary>
        public static string invite_other_guests {
            get {
                return ResourceManager.GetString("invite_other_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can invite other guests staying with you to join your vacation. Your guests can then do everything you can do:.
        /// </summary>
        public static string invite_others_info {
            get {
                return ResourceManager.GetString("invite_others_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name should be less than 50 characters.
        /// </summary>
        public static string last_name_maxlength_message {
            get {
                return ResourceManager.GetString("last_name_maxlength_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string last_name_required_message {
            get {
                return ResourceManager.GetString("last_name_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Map....
        /// </summary>
        public static string loading_map {
            get {
                return ResourceManager.GetString("loading_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Reviews....
        /// </summary>
        public static string loading_reviews {
            get {
                return ResourceManager.GetString("loading_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Your Stay....
        /// </summary>
        public static string loading_your_stay {
            get {
                return ResourceManager.GetString("loading_your_stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string maps {
            get {
                return ResourceManager.GetString("maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Invitation Code.
        /// </summary>
        public static string mobile_invitation_code {
            get {
                return ResourceManager.GetString("mobile_invitation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string mobile_invitation_code_required_message {
            get {
                return ResourceManager.GetString("mobile_invitation_code_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews.
        /// </summary>
        public static string no_reviews {
            get {
                return ResourceManager.GetString("no_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no reviews for this property.
        /// </summary>
        public static string no_reviews_message {
            get {
                return ResourceManager.GetString("no_reviews_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks, I&apos;ll continue here..
        /// </summary>
        public static string no_thanks {
            get {
                return ResourceManager.GetString("no_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connectivity is Required to Invite Other Guests..
        /// </summary>
        public static string offline_guests_message {
            get {
                return ResourceManager.GetString("offline_guests_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Info.
        /// </summary>
        public static string offline_info {
            get {
                return ResourceManager.GetString("offline_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connectivity is Required to Find Your Reservation..
        /// </summary>
        public static string offline_login_message {
            get {
                return ResourceManager.GetString("offline_login_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Internet Connectivity is Required for this feature. Please connect your device and try again..
        /// </summary>
        public static string offline_message {
            get {
                return ResourceManager.GetString("offline_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in maps.
        /// </summary>
        public static string open_in_maps {
            get {
                return ResourceManager.GetString("open_in_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the app.
        /// </summary>
        public static string open_the_app {
            get {
                return ResourceManager.GetString("open_the_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string overall {
            get {
                return ResourceManager.GetString("overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string overall_hidden {
            get {
                return ResourceManager.GetString("overall_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall is required.
        /// </summary>
        public static string overall_hidden_required_message {
            get {
                return ResourceManager.GetString("overall_hidden_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string property_hidden {
            get {
                return ResourceManager.GetString("property_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is required.
        /// </summary>
        public static string property_hidden_required_message {
            get {
                return ResourceManager.GetString("property_hidden_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your stay.
        /// </summary>
        public static string rate_your_stay {
            get {
                return ResourceManager.GetString("rate_your_stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more &gt;.
        /// </summary>
        public static string read_more {
            get {
                return ResourceManager.GetString("read_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey it looks like you are on a mobile device.
        /// </summary>
        public static string redirector_info {
            get {
                return ResourceManager.GetString("redirector_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your request. Please try again..
        /// </summary>
        public static string request_error_message {
            get {
                return ResourceManager.GetString("request_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Failure.
        /// </summary>
        public static string request_error_title {
            get {
                return ResourceManager.GetString("request_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Invitation Email.
        /// </summary>
        public static string resend_invitation_email {
            get {
                return ResourceManager.GetString("resend_invitation_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resending Your Reservation....
        /// </summary>
        public static string resending_your_reservation {
            get {
                return ResourceManager.GetString("resending_your_reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo.
        /// </summary>
        public static string select_photo {
            get {
                return ResourceManager.GetString("select_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string send_loading_text {
            get {
                return ResourceManager.GetString("send_loading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get excited for your upcoming vacation. To access your stay please enter the information provided in your invitation email..
        /// </summary>
        public static string sigin_info {
            get {
                return ResourceManager.GetString("sigin_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In Required.
        /// </summary>
        public static string sign_in_required {
            get {
                return ResourceManager.GetString("sign_in_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Access Rental below to sign into your stay.
        /// </summary>
        public static string tap_access_rental {
            get {
                return ResourceManager.GetString("tap_access_rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string terms_of_service {
            get {
                return ResourceManager.GetString("terms_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number to text a link to download the free HomeAway mobile app..
        /// </summary>
        public static string text_app_message {
            get {
                return ResourceManager.GetString("text_app_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your link has been texted to you..
        /// </summary>
        public static string text_app_success {
            get {
                return ResourceManager.GetString("text_app_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string text_app_success_title {
            get {
                return ResourceManager.GetString("text_app_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should be less than 128 characters.
        /// </summary>
        public static string title_maxlength_message {
            get {
                return ResourceManager.GetString("title_maxlength_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string title_required_message {
            get {
                return ResourceManager.GetString("title_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value_hidden {
            get {
                return ResourceManager.GetString("value_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        public static string value_hidden_required_message {
            get {
                return ResourceManager.GetString("value_hidden_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Access codes and content.
        /// </summary>
        public static string view_access_codes {
            get {
                return ResourceManager.GetString("view_access_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Review.
        /// </summary>
        public static string your_review {
            get {
                return ResourceManager.GetString("your_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message should be less than 4000 characters.
        /// </summary>
        public static string your_review_maxlength_message {
            get {
                return ResourceManager.GetString("your_review_maxlength_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        public static string your_review_required_message {
            get {
                return ResourceManager.GetString("your_review_required_message", resourceCulture);
            }
        }
    }
}
