//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladToHaveYou.Resources.MyStay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GladToHaveYou.Resources.MyStay.MyStayStrings", typeof(MyStayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Sent {1} Reminder.
        /// </summary>
        public static string ContentNotificationWasSent {
            get {
                return ResourceManager.GetString("ContentNotificationWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Will Be Sent {1} Reminder.
        /// </summary>
        public static string ContentNotificationWillBeSent {
            get {
                return ResourceManager.GetString("ContentNotificationWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Added To Stay.
        /// </summary>
        public static string GuestAddedToStay {
            get {
                return ResourceManager.GetString("GuestAddedToStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Cannot See Access My Rental, Find My Rental or Driving Directions.
        /// </summary>
        public static string GuestCannotAccessRental {
            get {
                return ResourceManager.GetString("GuestCannotAccessRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Invited Again To Stay.
        /// </summary>
        public static string GuestOfGuestInvitationFollowupWasSent {
            get {
                return ResourceManager.GetString("GuestOfGuestInvitationFollowupWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Will Be Invited Again To Stay.
        /// </summary>
        public static string GuestOfGuestInvitationFollowupWillBeSent {
            get {
                return ResourceManager.GetString("GuestOfGuestInvitationFollowupWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Was Invited To Stay.
        /// </summary>
        public static string GuestOfGuestInvitationWasSent {
            get {
                return ResourceManager.GetString("GuestOfGuestInvitationWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Will Be Invited To Stay.
        /// </summary>
        public static string GuestOfGuestInvitationWillBeSent {
            get {
                return ResourceManager.GetString("GuestOfGuestInvitationWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Wrote A Review.
        /// </summary>
        public static string GuestSignedGuestbook {
            get {
                return ResourceManager.GetString("GuestSignedGuestbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Information Not Provided.
        /// </summary>
        public static string InformationNotProvided {
            get {
                return ResourceManager.GetString("InformationNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation follow up was sent to reservation holder.
        /// </summary>
        public static string InvitationFollowupWasSent {
            get {
                return ResourceManager.GetString("InvitationFollowupWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation follow up will be sent to reservation holder.
        /// </summary>
        public static string InvitationFollowupWillBeSent {
            get {
                return ResourceManager.GetString("InvitationFollowupWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation was sent to reservation holder.
        /// </summary>
        public static string InvitationWasSent {
            get {
                return ResourceManager.GetString("InvitationWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation will be sent to reservation holder.
        /// </summary>
        public static string InvitationWillBeSent {
            get {
                return ResourceManager.GetString("InvitationWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide.
        /// </summary>
        public static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinvite.
        /// </summary>
        public static string Reinvite {
            get {
                return ResourceManager.GetString("Reinvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Review Followup Request Sent To {0}.
        /// </summary>
        public static string RequestForGuestbookFollowupWasSent {
            get {
                return ResourceManager.GetString("RequestForGuestbookFollowupWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Review Followup Request Will Be Sent To {0}.
        /// </summary>
        public static string RequestForGuestbookFollowupWillBeSent {
            get {
                return ResourceManager.GetString("RequestForGuestbookFollowupWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Review Request Sent To {0}.
        /// </summary>
        public static string RequestForGuestbookWasSent {
            get {
                return ResourceManager.GetString("RequestForGuestbookWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Review Request Will Be Sent To {0}.
        /// </summary>
        public static string RequestForGuestbookWillBeSent {
            get {
                return ResourceManager.GetString("RequestForGuestbookWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Section_After {
            get {
                return ResourceManager.GetString("Section_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string Section_Arrival {
            get {
                return ResourceManager.GetString("Section_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string Section_Departure {
            get {
                return ResourceManager.GetString("Section_Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Arrival.
        /// </summary>
        public static string Section_PreArrival {
            get {
                return ResourceManager.GetString("Section_PreArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay.
        /// </summary>
        public static string Section_Stay {
            get {
                return ResourceManager.GetString("Section_Stay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Message Was Sent To {0}.
        /// </summary>
        public static string ThankYouWasSent {
            get {
                return ResourceManager.GetString("ThankYouWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You Message Will Be Sent To {0}.
        /// </summary>
        public static string ThankYouWillBeSent {
            get {
                return ResourceManager.GetString("ThankYouWillBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message Was Sent To Reservation Holder.
        /// </summary>
        public static string WelcomeWasSent {
            get {
                return ResourceManager.GetString("WelcomeWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message Will Be Sent To Reservation Holder.
        /// </summary>
        public static string WelcomeWillBeSent {
            get {
                return ResourceManager.GetString("WelcomeWillBeSent", resourceCulture);
            }
        }
    }
}
